### ISSUE TITLE
Graphics window canvases don't fill the window

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glkote#12]
![glkote screenshot](https://cloud.githubusercontent.com/assets/59074/19151679/585e23fa-8c11-11e6-934f-701ef0c6f352.png)

![another screenshot](https://cloud.githubusercontent.com/assets/5066755/19410232/de21b4b2-92e6-11e6-9479-a2df14af577c.png)

This is surely due to some finicky css default rule. I haven't figured out yet how it should be fixed.

**Comment by erkyrath** [comment]
(Problem is the darker-blue line at the bottom edge. Or black on newer builds.)

**Comment by curiousdannii** [comment]
I'm pretty sure it's the space between the baseline and the bounding box, because the canvas is inline. Maybe all that needs changing is making it block? But I don't know what else that would affect.

**Comment by erkyrath** [comment]
Nothing else that I can think of. I will accept this as the right answer. :)

I'm pretty sure I thought canvas was display:block by default, when I wrote this code.

**Comment by erkyrath** [comment]
Try https://github.com/erkyrath/glkote/commit/f2a84f2e1221b13638fa2acbf5c73a3d35f24082 in your setup, see if it fixes the problem.

**Comment by curiousdannii** [comment]
Yep looks good to me.

I thought I had seen in the style sheets that it had been explicitly set to `display: inline`, but I must've just imagined it.
