### ISSUE TITLE
Alternative autosave format

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glkote#19]
I've been brainstorming about how I would like to implement autosaving in ZVM, and if the memory and stack start as typed arrays then it would make sense to keep them that way. What if an autosave file was a Quetzal file with an extra chunk of JSON data for the remaining VM properties, either stored as ASCII or as UTF-16 if necessary. (Not UTF-8 to simplify processing - although that would really be up to the VM.)

I'm raising this here because it would need a change to the Dialog libraries.

When Quixe changes to using typed arrays you may want to change the format as well. Though the 100MB+ blorbs are mostly media, and the VM's RAM would still fit in a JS Array so the current format would work.

**Comment by erkyrath** [comment]
Speaking of autosave, I note that glkapi.js triggers autosave through a GiDispa.check_autosave() hook. So ZVM may wind up needing a GiDispa layer just for that.

It wouldn't have to be the full gi_dispa.js library as it exists. I am constructing a minimal ZVM dispatcher just to see what would be needed; it currently looks like https://github.com/erkyrath/lectrote/blob/ifvms/ifvms/zvm_dispatch.js .

**Comment by curiousdannii** [comment]
Unless I've missed something I could easily set snapshot.ram to be the whole Quetzal file, and therefore the Dialog libraries wouldn't need to be changed. This would mean sticking with a misnamed ram property (or else it would be a semver major change), which I'm okay with.

I'm thinking I'll probably not put the JSON inside the Quetzal, there's no real need. And it won't be a real Quetzal file because the stack chunk will be a mix of little and big endian.

**Comment by erkyrath** [comment]
I'm not worried about the property names. You can assume that the same software is writing out and reading in the autosave file, so you just have to be consistent.

**Comment by curiousdannii** [comment]
I had meant that if Dialog ever changed from ram to a more generic property like bindata then it would cause problems because ZVM wouldn't have any way to know. But the purity of a rarely used property isn't worth the hassle of changing it!

**Comment by erkyrath** [comment]
I guess I could provide a more general way to distinguish binary-stored properties from json-stored ones. But for now I'll leave things the way they are.
