### ISSUE TITLE
localStorage errors are not caught

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glkote#20]
If the localStorage is full then the browser will throw, but dialog.js is not catching the errors.

Reported here: http://www.intfiction.org/forum/viewtopic.php?f=7&t=21040&start=20#p117664

**Comment by erkyrath** [comment]
We can catch 'em and have file_write() return false, but it won't necessarily be reported back to the game in any useful way. It looks like most file_write() calls happen in the background (gli_stream_flush_file). So the usual symptom of writing too many save files will be the data just silently disappears.

**Comment by angstsmurf** [comment]
Well, the main problem in this case is that the game stops at the quota exceeded error. Is there no way to make it keep going after a failed save?

**Comment by erkyrath** [comment]
Yes, I can do that much.

**Comment by curiousdannii** [comment]
Probably the best thing to do would be to switch to Indexed DB, which should allow around 50MB or more, depending on the browser. Support is up to 94% on iplayif.com.

Mozilla's [localForage](https://github.com/localForage/localForage) library looks like a really good option - it presents a simple key/value interface just like local storage, and falls back to local storage if necessary. It is 20KB minified, but the web sql driver should be able to be removed to cut that back even more.

**Comment by erkyrath** [comment]
I've added code to check whether localStorage.setItem succeeds. If it fails (as in a private window), the module will fall back to plain Javascript memory storage, with no persistence. This is reasonable for the private-window case.

I'll file IndexedDB as a separate feature request.

**Comment by angstsmurf** [comment]
With this fix, I was able to complete CM on my phone. Thanks a lot!
