### ISSUE TITLE
gridcharheight is sometimes calculated wrong

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glkote#22]
Sometimes the gridcharheight seems to be calculated wrong, with the result that the bottom row of a grid window is invisible. A rearrange event will result in the correct gridcharheight being calculated.

Video: https://youtu.be/GAGTW8BiOtE

**Comment by curiousdannii** [comment]
Might be related to this? https://github.com/erkyrath/lectrote/issues/83

**Comment by erkyrath** [comment]
Sounds like it. I haven't seen it on Mac, anyhow.

**Comment by erkyrath** [comment]
Turns out it was happening on Mac, but the calculation error was too small to make a visible difference. And only happening on Lectrote.

I have added a font_load_delay option to cover this case.
