### ISSUE TITLE
glk_request_line_event and non make_arg_array arrays

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glkote#24]
So I've run into a problem with [my new project](https://github.com/curiousdannii/emglken): Calling glkapi.js's glk_request_line_event doesn't work for arrays which haven't been passed to make_arg_array, and there doesn't seem to be an easy way to pass them to make_arg_array because neither it nor ArgInt/ArgChar are exposed on GiDispa. (We mustn't have ever tested ZVM with GiDispa or it wouldn't have worked.)

I see two options: expose those functions, or make retain_array not throw if it doesn't work. But I don't really understand the purpose of the system, so I don't know which option to take.

**Comment by curiousdannii** [comment]
Or another option would be to use remglk more fully and communicate directly with GlkOte rather than glkapi.js. But remglk isn't set up for doing file over JSON so it might just be trading one problem for another...

**Comment by erkyrath** [comment]
GDC is coming up so it may be a couple of weeks before I can look at this. Or maybe I'll get bored at GDC and look at it, but no bets...

**Comment by curiousdannii** [comment]
Of course.

I've tentatively edited GiDispa to ignore arrays it doesn't know about, and it seems to be working okay, though I don't know the full implications.

**Comment by erkyrath** [comment]
The point of this mess is this: When glkapi is used from Quixe, we can't just pass a JS array into glk_request_line_event and be happy. At some future time, the array is going to be filled out and copied back into Glulx memory. We need to keep a record of the VM address where that's going to happen.

This record is constructed in the code generated by build_function (the call to `self.make_arg_array`). Then glk_request_line_event calls `GiDispa.retain_array` to put it into a global list, where it will hang around until the line event completes.

I'd say that gi_dispa.js is specific to Quixe. It makes sense for you to fork it and make whatever changes are appropriate for emglken. If you never call make_arg_array(), then retain_array() can be a no-op.

**Comment by curiousdannii** [comment]
Closing with the advice that VMs provide their own GiDispa implementation.
