### ISSUE TITLE
Last space on the line collapses

### ISSUE THREAD

**Issue by erkyrath** [erkyrath/glkote#26]
When I set up the glkote HTML structure, I didn't use `white-space: pre-wrap` because it was 2008. Instead I used `&nbsp;` in the minimal number of places to preserve output spacing.

I *didn't* use `&nbsp;` for trailing spaces at the end of a line. This was a compromise -- a lot of games print trailing spaces on paragraphs, due to sloppy coding. If I change those to special characters, I'm making copy-and-paste significantly fuglier in a fairly common case. 

However, Dannii points out that Jigsaw uses meaningful trailing space when displaying the jigsaw pieces.

Obvious options:
- Switch to pre-wrap.
- Transform trailing spaces.
- Transform trailing spaces, but only in spans that have non-`normal` style.

**Comment by curiousdannii** [comment]
It would even be possible to use pre-wrap normally but switch to `normal` for the normal style. But I really don't think that's necessary. Parchment's been using pre-wrap for years now, and I haven't seen it have any problems with trailing spaces etc.

**Comment by erkyrath** [comment]
Pre-wrap it is. Change is checked in.
