### ISSUE TITLE
Undeclared fref variables

### ISSUE THREAD

**Issue by juhana** [erkyrath/glkote#34]
In two places variables called `fref` are used without declaring them first, which causes an error to be thrown in strict mode:

glk_fileref_create_temp https://github.com/erkyrath/glkote/blob/dd0c77dc79bbcc68537669f36da5ff2c9a90eb61/glkapi.js#L4896 

glk_fileref_create_by_name https://github.com/erkyrath/glkote/blob/dd0c77dc79bbcc68537669f36da5ff2c9a90eb61/glkapi.js#L4904

I don't think they need to be global variables so they could just be changed to `var fref`?

**Comment by erkyrath** [comment]
I've fixed these and a handful of other missing "var" declarations. Let me know if you run into any others.
