### ISSUE TITLE
Warn when saving in Safari that files will be deleted after 7 days

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glkote#38]
https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/

GlkOte should warn in Safari that files will be deleted after 7 days.

Ideally the save dialog should offer you the ability to download the savefile immediately too. Of course it doesn't have the file when the dialog is put up... so maybe set a variable/callback that pops up another dialog once glk_close_stream is called.

**Comment by erkyrath** [comment]
This is a real concern but wow, what a dance of checking browser identities and versions. No way to tell if other browsers will pick up this privacy scheme, too.

Maybe I should just add a general warning for all browsers.

**Comment by erkyrath** [comment]
Added warning: "data may be erased by clearing cookies or browser privacy policies"
