### ISSUE TITLE
Include the transcripts session data in the autosave state

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glkote#44]

**Comment by erkyrath** [comment]
What do we need to save? The recording_state.sessionId in glkote.js, I suppose. Do we also need label and format?

**Comment by curiousdannii** [comment]
I have no idea at all sorry.

**Comment by erkyrath** [comment]
No, it's fine, the questions were as much for myself as for you.

**Comment by curiousdannii** [comment]
Pretty sure all you need to do is save and restore the session id. That's what I'm now doing in AsyncGlk. More could be stored, but those other variables are normally obtained from the HTML itself, so if they're removed then it's probably because the person doesn't want transcripts any more.

**Comment by erkyrath** [comment]
Does https://github.com/erkyrath/glkote/commit/311c1a858362dfe48ec070db0286595939f51eb7 look right?

**Comment by curiousdannii** [comment]
Yeah that looks right to me. You might also like to add a log saying you're using the autorestored session, because the log that it makes for the initial session is not longer correct.

**Comment by erkyrath** [comment]
Done. Thanks.
