### ISSUE TITLE
Add reasonable default metrics

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glkote#45]
Unlike RemGlk, GlkApi can't handle an incomplete metrics definition, producing NaNs in `glk_window_get_size` (and probably other functions). It should ideally support incomplete metrics (such as just providing a width and height), giving reasonable defaults for the other properties.

**Comment by erkyrath** [comment]
Done.

**Comment by erkyrath** [comment]
The defaulting rules should be the same as in RemGlk.

**Comment by curiousdannii** [comment]
Thank you!

**Comment by curiousdannii** [comment]
One question: what will happen if you provide some metrics to the `init` event but not the `arrange` event? Will they be overwritten by the defaults? That's not an unreasonable option to take, but it could be confusing, so maybe an extra sentence in the docs explaining so?

**Comment by erkyrath** [comment]
There is no carry-over from one init/arrange event to the next. Each metrics object is taken on its own. I'll put a note somewhere.
