### ISSUE TITLE
Move Blorb functionality from Quixe's GiLoad to a Blorb class/library in this repo

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glkote#47]
GlkOte and GlkApi both depend on GiLoad, but purely for its Blorb functions. I think it would make more sense for those to be found in this repository, so that there aren't any external dependencies, and so Quixe isn't required for other VMs. It could be called "Blorb", but would also need to support the JSON external resources system.

**Comment by erkyrath** [comment]
Yes, good point. Will do.

**Comment by erkyrath** [comment]
The argument against moving the Blorb functionality to this repository is that it assumes the input will be a byte array. In practice, that will only come from GiLoad or something a lot like it.

Maybe this is arguing for moving the whole gi_load library over. I'm not sure I have that energy.

**Comment by curiousdannii** [comment]
For Parchment I have my own loading system, but GlkOte still needs Blorb support. (Which I don't think I have added yet actually.) GiLoad is quite opinionated in how it works. If you brought it here I still probably wouldn't use it in Parchment. Whereas Blorb support is more perfunctory - you initiate it with the data (byte array or JSON) and then pass its reference into GlkOte/GlkApi. It makes sense to me to think of Blorb as a component of the GlkOte display system, whereas GiLoad is a component of an IF app.

I'm not too sure what your point about it assuming the input will be a byte array is. (It should support JSON as well, right?) And while a demo page here might need something like GiLoad, the demos all contain a bunch of scaffolding that isn't considered part of GlkOte proper.

**Comment by erkyrath** [comment]
I hadn't gotten as far as thinking about the JSON system. :)

GlkOte doesn't *quite* need Blorb support -- it needs image info in the form that the Blorb module supplies. Having the Blorb library supply that, okay, it would be a very thin wrapper but it makes sense.

**Comment by curiousdannii** [comment]
GlkApi also needs it for resource streams. And image info? I think that's all the uses.

**Comment by erkyrath** [comment]
This is basically done -- see the blorblib branch of glkote, quixe, lectote repos. I haven't finished commenting the gi_blorb.js file, though.

It turned out to be more of a hassle than it looked. The JSON external resource model wasn't really up to snuff -- it was a quick hack that I did to support I7 and Quixe. There's a more flexible option in there now. Or there will be once I document it...

**Comment by curiousdannii** [comment]
That's awesome, thank you!
