### ISSUE TITLE
Mobile: No way to open the keyboard for very long prompts on very small screens

### ISSUE THREAD

**Issue by dfabulich** [erkyrath/glkote#53]
https://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fzcode%2FBronze.zblorb

On an iPod Touch 7th Generation simulator, the `<input>` line is a teeny tiny 1px-wide sliver on the right edge of the screen. Even with my PR #51, the `<input>` is nearly impossible to tap on, as the "Tap here to type" hint disappears off the right edge of the screen.

![Simulator Screen Shot - iPod touch (7th generation) - 2021-11-24 at 00 04 37](https://user-images.githubusercontent.com/96150/143198602-ef7143e1-6b35-48eb-adbb-b1bfee5297f9.png)

**Comment by vmiliantsei** [comment]
Possible fix: https://github.com/erkyrath/glkote/pull/71.
Inspired by https://github.com/garglk/garglk/blob/master/garglk/wintext.cpp#L1102.

**Comment by erkyrath** [comment]
Should be fixed now.
