### ISSUE TITLE
local storage: restore game from different path

### ISSUE THREAD

**Issue by IkeC** [erkyrath/glkote#75]
I have my game hosted on my site using Quixe (_/mygame/play.html_ -> _/mygame/interpreter/mygame.gblorb.js_), and I update it sometimes, so saves from players on previous versions won't work anymore. I would like to point them to a "previous version" so they can try to load their game there.

I thought I might be able to host the previous version in a subdirectory (/game/previous/play.html) along with all the files, but it won't find previous saves. Leaving it in the same directory using a different name doesn't work either (_/game/play-previous.html_ -> _/mygame/interpreter/mygame-previous.gblorb.js_).

(How) can it be done?

**Comment by erkyrath** [comment]
Finding the save files doesn't rely on the game file path or the game filename. It uses a checksum of the game header info. So hosting the previous version in a different location should work, as long as it's exactly the same gblorb.js file.

I'm not sure why you're having trouble. Possibly the browser has cleared old save files due to "clearing cookies" or expiring them due to age?

**Comment by IkeC** [comment]
Thanks for the quick reply!

It's not the same gblorb, that's the point. Player saves on Version 1 of the game. When I update to Version 2 (keeping the filename _game.gblorb_), I want to give the player the option to continue his Version 1 save on the Version 1 game that I moved elsewhere (either to a subdir like _/oldversion_ or using _game.oldversion.gblorb_).

I've seen that the value for _gameid_ is created from the game header as you say, so I would probably change that to a constant string or anything like that, not sure if that's the most elegant (or proper) way to do it though.

**Comment by IkeC** [comment]
Possibly still confusing I guess. The player above comes back, loads the updated Version 2 of the game (_game.gblorb_), and when he types restore, the Version 1 save should appear in the dialog (currently it won't). He tries to load that, it fails, and then I can show an error message in-game that he should click the "Previous Version" link on the left on the website and try restoring again.

**Comment by erkyrath** [comment]
Oh, I see.

No, the version 1 saves will never appear when trying to RESTORE in version 2. There's no way to connect them. They're just as alien as saves from Curses or any other game.

**Comment by IkeC** [comment]
In _function glk_fileref_create_by_prompt_ I changed
```
if (filetype == Const.fileusage_SavedGame)
    special.gameid = VM.get_signature();
```
to
```
if (filetype == Const.fileusage_SavedGame)
    special.gameid = 'MYGAME';
```
Not elegant, but it seems to work as expected - only for saves made after this change, of course.
